{
    "boardData": [
        [{
            "type": 4
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 4
        }],
        [{
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0,
            "tile": {
                "letter": "P",
                "id": 1,
                "class": "P",
                "points": 2
            },
            "placed": true
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }],
        [{
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, ],
        [{
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, ],
        [{
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }],
        [{
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }],
        [{
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, ],
        [{
            "type": 4
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 4
        }, ],
        [{
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, ],

        [{
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }],
        [{
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }],
        [{
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, ],
        [{
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, ],
        [{
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 2
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }],
        [{
            "type": 4
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 3
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 1
        }, {
            "type": 0
        }, {
            "type": 0
        }, {
            "type": 4
        }]
    ]
}
